<a href="https://colab.research.google.com/github/prady1900/Kaggle_Competition/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
import seaborn as sns

In [51]:
df = pd.read_csv('train.csv')

In [52]:
df.head()

POSTED_BY  UNDER_CONSTRUCTION  ...   LATITUDE  TARGET(PRICE_IN_LACS)
0     Owner                   0  ...  77.597960                   55.0
1    Dealer                   0  ...  76.644605                   51.0
2     Owner                   0  ...  77.632191                   43.0
3     Owner                   0  ...  77.344500                   62.5
4    Dealer                   1  ...  88.484911                   60.5

[5 rows x 12 columns]

In [5]:
df.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
ADDRESS                  0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [53]:
df.drop(['ADDRESS'], axis=1, inplace=True)

In [54]:
df.head()

POSTED_BY  UNDER_CONSTRUCTION  ...   LATITUDE  TARGET(PRICE_IN_LACS)
0     Owner                   0  ...  77.597960                   55.0
1    Dealer                   0  ...  76.644605                   51.0
2     Owner                   0  ...  77.632191                   43.0
3     Owner                   0  ...  77.344500                   62.5
4    Dealer                   1  ...  88.484911                   60.5

[5 rows x 11 columns]

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
enc = LabelEncoder()

In [57]:
dfle = df
dfle.iloc[:,[0,4]]

POSTED_BY BHK_OR_RK
0         Owner       BHK
1        Dealer       BHK
2         Owner       BHK
3         Owner       BHK
4        Dealer       BHK
...         ...       ...
29446     Owner       BHK
29447     Owner       BHK
29448    Dealer       BHK
29449     Owner       BHK
29450    Dealer       BHK

[29451 rows x 2 columns]

In [58]:
objList = dfle.select_dtypes(include = "object").columns
print (objList)

Index(['POSTED_BY', 'BHK_OR_RK'], dtype='object')


In [59]:
objList[:2]

Index(['POSTED_BY', 'BHK_OR_RK'], dtype='object')

In [60]:
for feat in objList:
    dfle[feat] = enc.fit_transform(dfle[feat].astype(str))

In [27]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(dfle))
print(z)

[[1.28713168 0.46813431 0.68271456 ... 1.34247787 0.07201136 0.13381461]
 [0.65335028 0.46813431 0.68271456 ... 1.45454064 0.01828927 0.1399041 ]
 [1.28713168 0.46813431 0.68271456 ... 1.37339983 0.07525368 0.15208308]
 ...
 [0.65335028 0.46813431 0.68271456 ... 0.90706647 0.09563692 0.1762888 ]
 [1.28713168 0.46813431 0.68271456 ... 1.35372005 0.32111704 0.11554615]
 [0.65335028 0.46813431 1.464741   ... 0.89152595 0.09433482 0.17522314]]


In [28]:
threshold =3
print(np.where(z>3))

(array([   34,    40,    40, ..., 29440, 29447, 29447]), array([ 7,  7, 10, ...,  7,  8,  9]))


In [61]:
dfle.tail()

POSTED_BY  UNDER_CONSTRUCTION  ...   LATITUDE  TARGET(PRICE_IN_LACS)
29446          2                   0  ...  78.043277                   45.0
29447          2                   0  ... -86.150721                   16.0
29448          1                   0  ...  75.828002                   27.1
29449          2                   0  ...  80.227910                   67.0
29450          1                   0  ...  75.841749                   27.8

[5 rows x 11 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test = train_test_split(dfle.iloc[:,:-1],dfle.iloc[:,-1:],test_size=0.2,random_state=101)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler= StandardScaler()
x_train = scaler.fit_transform(X_train)

In [40]:
dfle.describe()

POSTED_BY  UNDER_CONSTRUCTION  ...      LATITUDE  TARGET(PRICE_IN_LACS)
count  29451.000000        29451.000000  ...  29451.000000           29451.000000
mean       1.336695            0.179756  ...     76.837695             142.898746
std        0.515345            0.383991  ...     10.557747             656.880713
min        0.000000            0.000000  ...   -121.761248               0.250000
25%        1.000000            0.000000  ...     73.798100              38.000000
50%        1.000000            0.000000  ...     77.324137              62.000000
75%        2.000000            0.000000  ...     77.828740             100.000000
max        2.000000            1.000000  ...    152.962676           30000.000000

[8 rows x 11 columns]

In [42]:
dfle = dfle.rename(columns={"TARGET(PRICE_IN_LACS)":"Target"})

In [43]:
min_thresold, max_thresold = dfle.Target.quantile([0.001, 0.999])
min_thresold, max_thresold

(5.59, 9512.650000000067)

In [44]:
dfle[dfle.Target < min_thresold]

POSTED_BY  UNDER_CONSTRUCTION  RERA  ...  LONGITUDE    LATITUDE  Target
3882           2                   0     0  ...  12.720000   77.820000    0.85
8347           2                   0     1  ...  22.288976   73.128222    1.00
8435           2                   0     0  ...  21.000000   77.000000    4.90
10177          2                   0     0  ...  28.468976   77.026401    5.00
10678          2                   0     0  ...  21.778398   72.171336    5.00
11530          2                   0     0  ...  26.928785   75.828002    5.50
11729          2                   0     0  ...  58.691753 -117.001699    5.20
14036          2                   0     0  ...  20.282380   85.855363    0.25
15314          2                   0     0  ...  31.214709   75.766473    4.00
15544          2                   0     0  ...  21.168064   72.877148    5.00
16255          1                   0     0  ...  22.490000   72.660000    3.90
16977          2                   0     0  ...  20.579189   73.747096    4.00
17527          1                   0     0  ...  13.035200   77.577200    1.30
18350          1                   0     1  ...  26.707154   80.982346    4.50
18565          1                   0     0  ...  28.707966   77.487603    3.50
18773          2                   0     0  ...  23.050157   70.122999    5.00
19391          1                   0     0  ...  21.445354   70.910024    3.40
20434          0                   1     1  ...  18.454300   73.114700    2.00
20910          1                   1     0  ...  12.971321   77.598190    0.48
21416          1                   0     1  ...  26.707154   80.982346    4.50
22668          2                   0     0  ...  23.244599   87.083680    4.90
24424          0                   0     0  ...  18.963700   72.931400    4.90
25078          2                   0     0  ...  31.376481   75.538800    5.00
25582          2                   0     0  ...  25.025959   75.873414    5.00
27192          2                   0     0  ...  11.023232   76.979607    0.29
27339          1                   0     0  ...  22.490000   72.660000    4.00
27895          2                   0     1  ...  20.486943   75.724278    1.50
28366          1                   0     1  ...  26.707154   80.982346    4.50
28690          1                   0     0  ...  24.690280   78.418890    3.50
29308          0                   1     1  ...  18.454300   73.114700    2.00

[30 rows x 11 columns]

In [50]:
dfle[dfle.Target > max_thresold]

Empty DataFrame
Columns: [POSTED_BY, UNDER_CONSTRUCTION, RERA, BHK_NO., BHK_OR_RK, SQUARE_FT, READY_TO_MOVE, RESALE, LONGITUDE, LATITUDE, Target]
Index: []

In [47]:
dfle = dfle[(dfle.Target > max_thresold)&(dfle.Target < min_thresold)]

In [49]:
dfle.head(5)

Empty DataFrame
Columns: [POSTED_BY, UNDER_CONSTRUCTION, RERA, BHK_NO., BHK_OR_RK, SQUARE_FT, READY_TO_MOVE, RESALE, LONGITUDE, LATITUDE, Target]
Index: []

In [19]:
x_test = scaler.transform(X_test)

In [204]:
dfle.shape

(29451, 11)

In [209]:
x_train.shape

(23560, 10)

In [21]:
model = keras.Sequential()

model.add(keras.layers.Dense((10), activation='relu',input_shape=(10,)))
model.add(keras.layers.Dense((8), activation='relu'))
model.add(keras.layers.Dropout(0.2))
model.add(keras.layers.Dense((8), activation='relu'))
model.add(keras.layers.Dense((6), activation='relu'))
model.add(keras.layers.Dense(1))

model.compile(optimizer='adam', loss='mean_absolute_error')

In [22]:
model.fit(x_train,Y_train, epochs=200)

737/737 [==============================] - 1s 2ms/step - loss: 83.0037
Epoch 94/200
737/737 [==============================] - 2s 2ms/step - loss: 82.3882
Epoch 95/200
737/737 [==============================] - 1s 2ms/step - loss: 79.6684
Epoch 96/200
737/737 [==============================] - 1s 2ms/step - loss: 81.3128
Epoch 97/200
737/737 [==============================] - 1s 2ms/step - loss: 83.6234
Epoch 98/200
737/737 [==============================] - 1s 2ms/step - loss: 84.1305
Epoch 99/200
737/737 [==============================] - 1s 2ms/step - loss: 86.3129
Epoch 100/200
737/737 [==============================] - 1s 2ms/step - loss: 89.9069
Epoch 101/200
737/737 [==============================] - 1s 2ms/step - loss: 86.4049
Epoch 102/200
737/737 [==============================] - 2s 2ms/step - loss: 83.9532
Epoch 103/200
737/737 [==============================] - 1s 2ms/step - loss: 86.8795
Epoch 104/200
737/737 [==============================] - 1s 2ms/step - loss: 79.4326


In [23]:
predictions = model.predict(x_test)

In [24]:
from sklearn.metrics import r2_score

In [25]:
accuracy = r2_score(Y_test,predictions)
accuracy

0.35945796425462717